---
- name: Clone dotfiles git repository.
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    version: "{{ version }}"
    accept_hostkey: "{{ accept_hostkey }}"
  become: false

- name: Get the list of dotfiles from the installation directory.
  shell: "ls -dA {{ dest }}/.* | xargs -n 1 basename"
  register: dotfiles_list
  become: false
  changed_when: false

- name: Create symlinks for dotfiles.
  ansible.builtin.file:
    src: "{{ dest }}/{{ item }}"
    dest: "{{ installation_dir }}/{{ item }}"
    mode: 0644
    state: link
    force: true
  with_items: "{{ dotfiles_list.stdout_lines }}"
  when:
    - item != "."
    - item != ".."
