---
- name: Check if the dotfiles directory exist
  ansible.builtin.stat:
    path: "{{ dest }}"
  register: d

- name: Clone dotfiles git repository.
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    version: "{{ version }}"
    accept_hostkey: "{{ accept_hostkey }}"
  become: false
  when: d.stat.isdir is not defined

- name: Update dotfiles git repository.
  ansible.builtin.git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    version: "{{ version }}"
    accept_hostkey: "{{ accept_hostkey }}"
    update: true
    clone: false
    force: true
  become: false
  when: d.stat.isdir is defined and d.stat.isdir

- name: Get the list of dotfiles from the installation directory.
  ansible.builtin.shell: "ls -dA {{ dest }}/.* | xargs -n 1 basename"
  register: dotfiles_list
  become: false
  changed_when: false

- name: Create symlinks for dotfiles.
  ansible.builtin.file:
    src: "{{ dest }}/{{ item }}"
    dest: "{{ installation_dir }}/{{ item }}"
    mode: 0644
    state: link
    force: true
  with_items: "{{ dotfiles_list.stdout_lines }}"
  when:
    - item != "."
    - item != ".."
    - item != ".git"
